module Settings
  MINUTES_PLAYED = 17.0
  THREE_POINT_AVERAGE = 0.4
  TWO_POINT_AVERAGE = 0.5
  FOUL_AVERAGE = 0.7
  REBOUND_AVERAGE = 6.0
  STEAL_AVERAGE = 1.0
  BLOCK_AVERAGE = 1.0
  TURNOVER_AVERAGE = 2.5
  PERSONAL_FOUL_AVERAGE = 3.0
end